### ISSUE TITLE
Query fails randomly

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [xPaw/PHP-Source-Query#137]
Queries made seem to fail randomly.

I'm querying a source engine server and it works 75% of the time and fails the rest for no reason.

Changing the timeout makes no difference.
I'm using the code in the examples.

```
xPaw\SourceQuery\Exception\InvalidPacketException at line 47

Failed to read any data from socket

#0 /srv/web-apps/public_html/web-apps/empires/SourceQuery/Socket.php(76): xPaw\SourceQuery\BaseSocket->ReadInternal(Object(xPaw\SourceQuery\Buffer), 1400, Array)
#1 /srv/web-apps/public_html/web-apps/empires/SourceQuery/SourceQuery.php(210): xPaw\SourceQuery\Socket->Read()
#2 /srv/web-apps/public_html/web-apps/empires/server.php(11): xPaw\SourceQuery\SourceQuery->GetInfo()
#3 {main} 
```

**Comment by Engineer-of-Stuff** [comment]
Do you have any suggestions on how to fix this?
