### ISSUE TITLE
GetRules( ) not Working on Arma3

### ISSUE THREAD

**Issue by Sk3y** [xPaw/PHP-Source-Query#93]
Hi,

its work on altis.e-monkeys.com:2303 but not on 1.rnmail.de:2353.

You know the problem?
```
Paw\SourceQuery\Exception\InvalidPacketException at line 47
Failed to read any data from socket

#0 /var/www/new_hp/classes/SourceQuery/Socket.php(76): xPaw\SourceQuery\BaseSocket->ReadInternal(Object(xPaw\SourceQuery\Buffer), 1400, Array)
#1 /var/www/new_hp/classes/SourceQuery/SourceQuery.php(422): xPaw\SourceQuery\Socket->Read()
#2 /var/www/new_hp/test.php(34): xPaw\SourceQuery\SourceQuery->GetRules()
#3 {main}
```

**Comment by xPaw** [comment]
Server misconfiguration or something like that, unrelated to the library.
